spring:
  profiles:
    default: local

---

spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect # MySQL Dialect 설정

  datasource:
    url: jdbc:h2:tcp://localhost/~/myGarden;MODE=MySQL;DATABASE_TO_LOWER=TRUE #mysql 모드 설정, 대소문자 구분 안함 (다 소문자로 처리)
    driver-class-name: org.h2.Driver
    username: sa
    password:

application:
  security:
    jwt:
      secret-key: SHl1bmdnaUh5dW5nZ2lTYW1wbGVTYW1wbGVDb2RlQ29kZUh5dW5nZ2lIeXVuZ2dpU2FtcGxlU2FtcGxlQ29kZUNvZGU=
      expiration: 1800000 # 30 minutes
      refresh-token:
        expiration: 604800000 # 7 days

actuator:
  url: /api/actuator
  email: actTest@test.com

server:
  tomcat: #  tomcat 메트릭 설정 on. 톰캣 메트릭은 tomcat. 으로 시작
    mbeanregistry: # 톰캣 메트릭을 모두 사용하려면 다음 옵션을 켜야하며, 옵션을 켜지 않으면 tomcat.session. 관련정보만 노출됩니다
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "prometheus" #  이 설정은 모든 Actuator 엔드포인트를 외부에 노출
      base-path: ${actuator.url} # Actuator 엔드포인트의 기본 경로 지정
  server:
    port: 9089 # Actuator 엔드포인트가 서비스될 서버의 포트

---
application:
  security:
    jwt:
      secret-key: ${jwt.secret-key}
      expiration: ${jwt.expiration}
      refresh-token:
        expiration: ${jwt.refresh-expiration}

config:
  type: aws-parameterstore:/config/myGarden/

spring:
  config:
    activate:
      on-profile: prod
    import: ${config.type}
  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: ${jdbc.url}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${jdbc.username}
    password: ${jdbc.password}

server:
  port: 443
  ssl:
    key-store: classpath:ssl/keystore.p12
    key-store-type: PKCS12
    key-store-password: ${ssl.password}
  tomcat:
    mbeanregistry:
      enabled: true

actuator:
  url: ${actuator-param.url}
  port: ${actuator-param.port}
  email: ${actuator-param.email}

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
      base-path: ${actuator.url}
  server:
    port: ${actuator.port}

my-garden:
  slack:
    incoming-webhook-token: ${slack-incoming-webhook.url}
