spring:
  profiles:
    default: local, test

---

spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect # MySQL Dialect 설정

  datasource:
    url: jdbc:h2:tcp://localhost/~/myGarden;MODE=MySQL;DATABASE_TO_LOWER=TRUE #mysql 모드 설정, 대소문자 구분 안함 (다 소문자로 처리)
    driver-class-name: org.h2.Driver
    username: sa
    password:

---
application:
  security:
    jwt:
      secret-key: ${jwt.secret-key}
      expiration: ${jwt.expiration}
      refresh-token:
        expiration: ${jwt.refresh-expiration}

config:
  type: aws-parameterstore:/config/myGarden/

spring:
  config:
    activate:
      on-profile: prod
    import: ${config.type}
  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: ${jdbc.url}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${jdbc.username}
    password: ${jdbc.password}

server:
  port: 443
  ssl:
    key-store: classpath:ssl/keystore.p12
    key-store-type: PKCS12
    key-store-password: ${ssl.password}
