name: Vue build test

on:
  pull_request:
    branches:
      - dev
      - master
#    paths:
#      - my-garden-fe/**

env:
  NODE_VERSION: 20 # build.gradle에 정의된 nodeVersion과 일치시켜야 함

jobs:
  front-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./my-garden-fe

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node modules
        id: cache
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build with npm
        run: npm run build
