name: Vue build test with Gradle

on:
  pull_request:
    branches:
      - master
    paths:
      - my-garden-fe/**

jobs:
  front-test-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Grant execute permission for gradlew
        run: chmod +x my-garden-be/gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@ec92e829475ac0c2315ea8f9eced72db85bb337a # v3.0.0

      - name: Cache node modules
        uses: actions/cache@v3
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('my-garden-fe/package-lock.json') }}

      - name: add env(NPM_BUILD_CACHE) if cache hit
        if: steps.cache.outputs.cache-hit == 'true'
        run: echo "true" >> $NPM_BUILD_CACHE

      - name: npmBuild with Gradle (with npm install)
        if: steps.cache.outputs.cache-hit == 'false'
        run: ./my-garden-be/gradlew npmBuildWithInstall

      - name: npmBuild with Gradle (without npm install)
        if: steps.cache.outputs.cache-hit == 'true'
        run: ./my-garden-be/gradlew npmBuildWithoutInstall
