name: Vue build test

on:
  pull_request:
    branches:
      - dev
      - master
#    paths:
#      - my-garden-fe/**

env:
  NODE_VERSION: 20 # build.gradle에 정의된 nodeVersion과 일치시켜야 함

jobs:
  front-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: my-garden-fe/package-lock.json

      - name: Check if node_modules is cached
        id: cache-check
        run: |
          if [ -d node_modules ]; then
            echo "::set-output name=exists::true"
          fi

      - name: Install Dependencies
        if: steps.cache-check.outputs.exists != 'true'
        run: npm ci
        working-directory: my-garden-fe

      - name: Build with npm
        run: npm run build
        working-directory: my-garden-fe

